### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by susieggrim** [Susana-Gutierrez/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Select a car design.
- [x] Select page background.
- [x] Add car to the page.
- [x] Ensure that refreshing the page shows the same view as before refreshing.
- [x] Remove all CSS styling that had no effect or was unnecessary.
- [x] Test all functionality again in a private browsing section.
- [x] Fix all errors.
