### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by susieggrim** [Susana-Gutierrez/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [ ]  Ensure car rotates when user presses arrow keys.
- [ ] Ensure that refreshing the page shows the original car position.
- [ ]  Remove all CSS styling that had no effect or was unnecessary.
- [ ]  Test all functionality again in a private browsing section.
- [ ]  Fix all errors.
