### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by susieggrim** [Susana-Gutierrez/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Make sure the car moves few pixel every 16 milliseconds when user presses space.
- [x] Ensure that refreshing the page shows the same view as before refreshing.
- [x] Remove all CSS styling that had no effect or was unnecessary.
- [x] Test all functionality again in a private browsing section.
- [x]  Fix all errors.
