### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by susieggrim** [Susana-Gutierrez/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Make sure the car stops if user presses space.
- [x] Ensure car goes off the page if user doesn't stop the car.
- [x] Ensure that refreshing the page shows the same view as before refreshing.
- [x] Remove all CSS styling that had no effect or was unnecessary.
- [x] Test all functionality again in a private browsing section.
- [x] Fix all errors.
