### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by susieggrim** [Susana-Gutierrez/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Make sure the car can turn and move to the direction is facing. 
- [x]  Ensure that refreshing the page shows the same view as before refreshing.
- [x]  Remove all CSS styling that had no effect or was unnecessary.
- [x]  Test all functionality again in a private browsing section.
- [x]  Fix all errors.
